phone_mcc:              '000' # Refer to below sites to get the most accurate data for your SIM.
phone_mnc:              '000' # http://www.mcc-mnc.com/ AND http://en.wikipedia.org/wiki/Mobile_country_code
phone_country_code:     'US'
phone_language_code:    'en'
phone_number:           '919822012345' # With country code without + or 00
wh_nickname:            'Vader'

wh_md5:                 'Vu6nzOKzMttaMOYKo7YkEw=='
wh_version:             '2.11.419'
wh_device:              'Android'
wh_user_agent:          'WhatsApp/2.11.419 Android/4.3 Device/GalaxyS3'

wh_challenge_file:      'nextChallenge.dat' # This can be renamed to something more specific to the phone number like 919822012345Chal.dat
wh_debug:               'true'
wh_code_request_method: 'sms'

app_time_zone:          'Asia/Kolkata'
disable_auto_update:    'true'

# TODO: Upon successful registration, we can append wh_identity and wh_password to the file, hence completing the config.
# TODO: Status message, and display pic (via URL) can be set from here.